const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const storage = new Map();
const stub = {addEventListener(){}};
const ctx = {console, document:{getElementById(){return stub;},addEventListener(){}},window:{matchMedia(){return {matches:true};},addEventListener(){}},location:{search:''},localStorage:{getItem(k){return storage.get(k);},setItem(k,v){storage.set(k,v);}}};
vm.createContext(ctx);
let source = fs.readFileSync('docs/game.js','utf8');
const expose = `globalThis.g={startGame,scenarios:SCENARIOS,bestKey,saveBest,loadBest,state(){return S;},finish(){transferScreen=function(){};render=function(){};resultsScreen();return S.result;}}; introScreen=function(){S.scens[S.scen]=newScenRecord();}; h=function(){return {appendChild(){},style:{}};};`;
source = source.replace(/titleScreen\(\);\s*\}\)\(\);\s*$/, expose+'})();');
vm.runInContext(source,ctx);
const g=ctx.g;
for(let i=0;i<3;i++){
 g.startGame(i);
 assert.equal(g.state().scen,i);
 assert.equal(g.state().single,true);
 assert.equal(g.state().scens.filter(Boolean).length,1);
 assert.equal(g.state().kept,0);
 const result=g.finish();
 assert.ok(result.max>0 && result.max<315);
 assert.equal(result.score,0);
 assert.ok(g.bestKey().endsWith('-'+g.scenarios[i].id));
 g.saveBest({v:3,score:20+i});
 assert.equal(g.loadBest().score,20+i);
}
g.startGame();
assert.equal(g.state().single,false);
assert.equal(g.state().scen,0);
assert.equal(g.loadBest(),null);
assert.equal(g.finish().max,315);
assert.equal(storage.size,4);
assert.match(source,/var isLast = S.single \|\| S.scen === SCENARIOS.length-1/);
console.log('PASS: all three direct starts, independent records, single and full-run totals, isolated best scores, and completion routing');
